services:
- docker
language: go
go:
- 1.9
env:
  matrix:
  - OKARCH=amd64 OSARCH=amd64
  global:
  - VERSION=${TRAVIS_TAG}
  - GH_USER=${TRAVIS_REPO_SLUG%/*}
  - GH_APP=${TRAVIS_REPO_SLUG#*/}
  - JFROG_CLI_OFFER_CONFIG=false
before_install:
- sudo apt-get -qq update
- mkdir -p ${GOPATH}/bin
- cd ~
install:
- mkdir -p $GOPATH/src/github.com/mh-cbon/go-bin-rpm
- cd $GOPATH/src/github.com/mh-cbon/go-bin-rpm
- git clone https://github.com/mh-cbon/go-bin-rpm.git .
- go get
- go install
- cd $GOPATH/src/github.com/${TRAVIS_REPO_SLUG}
- go get
- go install
script: echo "pass"
before_deploy:
- docker pull fedora
- mkdir -p build/$OSARCH
- GOOS=linux GOARCH=$OKARCH go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$GH_APP
  main.go
- cp $GOPATH/bin/go-bin-rpm tmp
- |
  docker run -v $PWD:/mnt/travis fedora /bin/sh -c "cd /mnt/travis && (curl -s -L https://bintray.com/bincrafters/public-rpm/rpm > /etc/yum.repos.d/w.repo) && dnf install go-bin-rpm changelog rpm-build -y --quiet && go-bin-rpm generate --file rpm.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.rpm"
- rm -f ./tmp
- cp $GH_APP-$OSARCH-$VERSION.rpm $GH_APP-$OKARCH.rpm
- curl -fL https://getcli.jfrog.io | sh
- ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/rpm
  $GH_USER/rpm/$GH_APP || echo "package already exists"
- ./jfrog bt upload --override=true --key $BTKEY --publish=true $GH_APP-$OSARCH-$VERSION.rpm
  $GH_USER/rpm/$GH_APP/$VERSION pool/$POOL/$GH_APP/
- curl -X POST -u ${GH_USER}:${BTKEY} https://api.bintray.com/calc_metadata/${GH_USER}/rpm
deploy:
  provider: releases
  api_key:
    secure: CY2nebPdr2CSCZW34QCtlw/IdbaHl5T77xPFlmvXB2Z+0SnO0RTW7JvFMa2mDYxa6ibZ6dR2br9YwdgJYnqV+PnXCizvZ5KPqpHxE31ta4s1IokZr+v9J+deGvUdk60oF5mxkqcGgAtScEGC5ZVJ/0EqAn64o4+H3fOQfA1pYTpzUBL/c9yUNqAFLFDVXz1sd7eSccPwf1uthdhndybMgatogfQuUBmm3vNJYYheAF8XCimBmrsIkPed+OKfhkDqUCTdgSTOQWvv0Uf8ib5VUH0w+UV8Wx69/KNKVhp/f7Nhf6GCKT1AKh/fQxjpRaWdkQLsn7nqPVuF0dHYV/mtdo4EP0FDj+2a3LvtGpEst90Mo0SRzauhqCQqCopyOf3JKkKPqTyMRDKAzYWAymjeLGaPda4wOxNROWV7yBuXNTTUmU2GDPUMULnLA7v+0ml6wd3gGCOMU5It8Iynkuxts8ATlpa0qels3memQITfhkTdR3CFT2mr/frkDiVOtqnp6BJoQIjhSMXoMRfnSpnNOszsiLNa9pM+hNG3HeZN0MQ+gTlRgqmTSitvllr751oUhgNzjv35FDxaywFwKlqtaJfX9UVCLxcBTvDcP4ZKHJRbgFOmffv2mnKi1S8K26LUkuLZDKvCZgrw8iM1KjvPX/GP9tXaxgLrfsfQOcOGGGs=
  file_glob: true
  file:
  - $GH_APP-$OKARCH.rpm
  skip_cleanup: true
  overwrite: true
  true:
    tags: true
  on:
    repo: aurimasl/hfit
    tags: false
    all_branches: true
notifications:
  email: false
